version: '3'

services:
    apt-dater:
        image: netresearch/apt-dater
        build: .
        volumes:
            - ~/.ssh/id_rsa:/opt/apt-dater/id_rsa1
            - ./hosts.d:/opt/apt-dater/hosts.d
            - ./history:/opt/apt-dater/history
            - ./stats:/opt/apt-dater/stats
