version: '3'

services:
    apt-dater:
        image: repository.netresearch.de/admin/apt-dater
        build: .
        volumes:
            - ~/.ssh/id_rsa:/opt/apt-dater/id_rsa1
            - ./hosts.d:/opt/apt-dater/hosts.d
